Blog/Blog/Areas/Manager/Controllers/GuvenlikController.cs
using Blog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Blog.Areas.Manager.Controllers
{
    public class GuvenlikController : Controller
    {
        bloggerEntities db = new bloggerEntities();
        // GET: Manager/Guvenlik
        public ActionResult GirisYap()
        {


            return View();
        }

        [HttpPost]
        public ActionResult GirisYap(yazar y)
        {
            var bilgiler = db.yazar.FirstOrDefault(x => x.email == y.email && x.sifre == y.sifre);
            if (bilgiler !=null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.email,false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }

            
        }
    }
}

Blog/Blog/Areas/Manager/Views/Guvenlik/GirisYap.cshtml
@model Blog.Models.yazar
@{
    ViewBag.Title = "GirisYap";
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="~/Content/Admin/img/favicon.png">
    <title>FlatLab - Flat & Responsive Bootstrap Admin Template</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/Admin/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/Admin/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="~/Content/Admin/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/Content/Admin/css/style.css" rel="stylesheet">
    <link href="~/Content/Admin/css/style-responsive.css" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
    <script src="~/Content/Admin/js/html5shiv.js"></script>
    <script src="~/Content/Admin/js/respond.min.js"></script>
    <![endif]-->
</head>
<body class="login-body">
    <div class="container">

        <div class="form-signin">
            @using (Html.BeginForm("GirisYap", "Guvenlik", FormMethod.Post))
            {

                <h2 class="form-signin-heading">Giriş Yap</h2>
                <div class="login-wrap">
                    <input type="text" class="form-control" name="email" placeholder="E-Mail" autofocus>
                    <input type="password" class="form-control" name="sifre" placeholder="Şifre">
                    <button class="btn btn-lg btn-login btn-block" type="submit">Açın Kapıyı</button>



                </div>

            }
        </div>

        </div>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/Content/Admin/js/jquery.js"></script>
    <script src="~/Content/Admin/js/bootstrap.min.js"></script>

</body>
</html>